sonar.projectKey=leaflet-notes-app
sonar.projectName=Leaflet Notes App
sonar.sources=frontend/src,backend/src
sonar.tests=frontend/src/test,backend/test
sonar.exclusions=**/test/**,**/tests/**,**/node_modules/**,**/dist/**,**/coverage/**,**/.scannerwork/**
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
sonar.host.url=http://localhost:9000